/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117612-gc98810ab47-20241018"
#endif /* AVUTIL_FFVERSION_H */
